version: "3.9"

services:
  pendulum:
    build:
      context: .
      dockerfile: dockerfile.pendulum
    container_name: pendulum-service
    ports:
      - "50051:50051"

  control:
    build:
      context: .
      dockerfile: dockerfile.control
    container_name: control-service
    depends_on:
      - pendulum