version: "3.9"

services:
  pendulum:
    build:
      context: .
      dockerfile: dockerfile.pendulum
    container_name: pendulum-service
    ports:
      - "50051:50051"

  control:
    build:
      context: .
      dockerfile: dockerfile.control
    container_name: control-service
    depends_on:
      - pendulum

  orch:
    build:
      context: .
      dockerfile: dockerfile.orch
    container_name: orch-service
    depends_on:
      - pendulum
      - control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data